"""Refatoracao para PT-BR

Revision ID: 1d90db490e6d
Revises: 77982b46ef92
Create Date: 2026-03-21 21:19:29.047989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d90db490e6d'
down_revision: Union[str, Sequence[str], None] = '77982b46ef92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_telefone'), 'clientes', ['telefone'], unique=False)
    op.create_table('fundos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('espessura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('largura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('altura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundos_id'), 'fundos', ['id'], unique=False)
    op.create_table('molduras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.Column('tamanho_barra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('largura_barra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_molduras_codigo'), 'molduras', ['codigo'], unique=True)
    op.create_index(op.f('ix_molduras_id'), 'molduras', ['id'], unique=False)
    op.create_table('suplementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_suplementos_id'), 'suplementos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=True),
    sa.Column('esta_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nome_usuario'), 'usuarios', ['nome_usuario'], unique=True)
    op.create_table('vidros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espessura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('incolor', 'antireflexo', 'espelho', 'outro', name='tipovidro'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('largura_chapa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('altura_chapa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vidros_id'), 'vidros', ['id'], unique=False)
    op.drop_index(op.f('ix_backgrounds_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    op.drop_index(op.f('ix_supplements_id'), table_name='supplements')
    op.drop_table('supplements')
    op.drop_index(op.f('ix_glasses_id'), table_name='glasses')
    op.drop_table('glasses')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_frames_code'), table_name='frames')
    op.drop_index(op.f('ix_frames_id'), table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('frames',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=False),
    sa.Column('bar_size', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('bar_width', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_id'), 'frames', ['id'], unique=False)
    op.create_index(op.f('ix_frames_code'), 'frames', ['code'], unique=1)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('glasses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thickness', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.VARCHAR(length=11), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('sheet_width', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('sheet_height', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glasses_id'), 'glasses', ['id'], unique=False)
    op.create_table('supplements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_supplements_id'), 'supplements', ['id'], unique=False)
    op.create_table('backgrounds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('thickness', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('width', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('height', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backgrounds_id'), 'backgrounds', ['id'], unique=False)
    op.drop_index(op.f('ix_vidros_id'), table_name='vidros')
    op.drop_table('vidros')
    op.drop_index(op.f('ix_usuarios_nome_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_suplementos_id'), table_name='suplementos')
    op.drop_table('suplementos')
    op.drop_index(op.f('ix_molduras_id'), table_name='molduras')
    op.drop_index(op.f('ix_molduras_codigo'), table_name='molduras')
    op.drop_table('molduras')
    op.drop_index(op.f('ix_fundos_id'), table_name='fundos')
    op.drop_table('fundos')
    op.drop_index(op.f('ix_clientes_telefone'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
