"""Initial migration

Revision ID: 77982b46ef92
Revises: 
Create Date: 2026-03-21 21:09:45.440175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77982b46ef92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backgrounds_id'), 'backgrounds', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_table('frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('bar_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bar_width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_code'), 'frames', ['code'], unique=True)
    op.create_index(op.f('ix_frames_id'), 'frames', ['id'], unique=False)
    op.create_table('glasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('incolor', 'antireflexo', 'espelho', 'outro', name='glasstype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sheet_width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sheet_height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glasses_id'), 'glasses', ['id'], unique=False)
    op.create_table('supplements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_supplements_id'), 'supplements', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supplements_id'), table_name='supplements')
    op.drop_table('supplements')
    op.drop_index(op.f('ix_glasses_id'), table_name='glasses')
    op.drop_table('glasses')
    op.drop_index(op.f('ix_frames_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_code'), table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_backgrounds_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
